name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Add x86_64 target
        run: rustup target add x86_64-apple-darwin

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build Installer
        run: make

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Fern-MCP-Installer.dmg
